### ISSUE TITLE
Top 45 coding fails in Rabbit!

### ISSUE THREAD

**Issue by Yonom** [Decagon/Rabbit#23]
# Rabbit fails

Rabbit is an awesome library, however its code includes many small issues that annoy me every time I look at the code. So here are the top 45 coding fails in Rabbit!

And yes, I was extremely bored!
## #1: GameId is hardcoded in ArmorGames.cs

It should be replaced with `RabbitAuth.GameId`.
## #2: GameId is hardcoded in MouseBreaker.cs

It should be replaced with `RabbitAuth.GameId`.
## #3: GameId is hardcoded in UserName.cs

It should be replaced with `RabbitAuth.GameId`.
## #4: ArmorGames class is not thread safe

Between the assignment of `Client` and the `return Client;` statement, the value of `Client` can be changed. A lock or something similar should be used to prevent this from happening.
## #5: ArmorGames.Client property causes memory leaks

Because the value of `ArmorGames.Client` is only used in Authenticate method, it can be removed entirely and replaced with a local variable.
## #6: ArmorGames exceptions are ignored

Any exception thrown in `OnMessage` handlers of PlayerIO is ignored, same goes with the `AuthenticationException` that the handler might throw.
## #7: If ArmorGames auth fails, memory leaks happen

Because `c.Disconnect();` is only called if the login succeeds, the connection might stay open if the auth fails.
## #8: Login data for the guest user is hardcoded twice!

It is hardcoded in both `UserName` and `ArmorGames` classes.
## #9: ARMORGAMES LOGIN DOESN'T WORK, AT ALL!

Yes, it always returns null. :p But don't forget to set this one's priority to the lowest, who cares about failing logins when there are super rare memory leaks to fix anyway?
## #10: RabbitAuth.LogOn`s password parameter is optional

This is useless because there is no way of accessing this method without the optional parameter because there is already a method overload without the parameter. Simply remove the `= null` part to fix.
## #11: RabbitAuth.AuthenticationType is static

How come this one property is static and all others are not. This also might introduce race issues. **Very important!**
## #12: RabbitAuth keeps a copy reference to the Client

Why?
## #13: RabbitAuth keeps a copy reference to the Connection

Okay this one is actually serious! This prevents every object that has a `OnMessage` listener on the returned Connection to get garbage collected.
## #14: If the email is null, a NullRefrenceException is thrown

I'm trying to do kong login and I don't even know what to put in the email field instead o.O
## #15: Using StringComparision.CurrentCulture in RabbitAuth

This basically means "don't make this equation behave the same way on every machine".
## #16: RabbitAuth.LogOn might return PlayerIOError

And that is not even documented...
## #17: OnMessageHandler in RabbitAuth is public

Why?
## #18: OnMessageHandler in RabbitAuth has no code

It does nothing, is useless and can be removed.
## #19: There is no Auth class for Regular auth

Why not? D:
## #20: Creating worlds does not work

Okay, here is another low priority one. If there are no people in the room, the room creation fails due to the new restricted database access.
## #21: UserName class is inside Username.cs class

Wrong casing, see it?!
## #22: UserName class uses StringComparison.CurrentCulture

Same as #15
## #23: No "swapit" account type support

Nobody ever knew that there was an account type called "swapit", until they read the 23rd issue on this page, but even if it isn't supported anymore since over 3 years, there are still EE accounts registered on it (these people cant even access EE anymore but thats not the point, they surely want bots more than anything else)
## #24: Mousebreaker login does not work

Yup, it requires a userName for some reason, but the auto detection accepts a base64 string only.
## #25: StringComparison.CurrentCulture in Mousebraker

Same as #15
## #26: Wrong message is returned for Mousebreaker if the username is not a mousebreaker account

And if the user does not exist like the exception suggests, it returns a PlayerIOError instead!
## #28: UserName class casts Nullable<int> to int instead of using the Value property

`(int)i` should be replaced with `i.Value`.
## #29: UserName class does not work with anything but SimpleConnect

But it pretends to! It looks like it can support many login types.
## #30: IdParser says PW01 is not a valid world id

But it is!!! :(
## #31: IdParser does not support open worlds

Open worlds are one of the most important features in everybody edits, they are the reasoning behind the name of the game!
## #32: IdParser throws invalid null exception

ArgumentNullException's first parameter is not a message! It's the name of the parameter that is invalid.
## #33: IdParser throws no exceptions if the worldId is whitespace

It throws an error if it is empty, but accepts whitespace and treats them like empty strings? (It uses `String.Trim`)
## #34: FormatException thrown by IdParser does not have its InnerException property set

It is thrown after a UriFormatException is cought and it should provide this exception as the inner exception on the FormatException it throws.
## #35: IdParser uses CultureInfo.CurrentCulture

See #15
## #36: AppHarbor builds rabbit using the Debug configuration

OH GOD ALL THE JIT OPTIMIZATIONS ARE DISABLED D:
## #37: Rabbit builds on NuGet use the Debug configuration

OH GOD!
## #38: When built on Release configuration, the retry notifications are not displayed in the debug window.

Not that every end user has visual studio attached to every software they run just to read the debug output anyway, but hey! It's still a fail!
## #39: Retry notifications that appear when UnstableNetwork is set are not displayed to the user

Nor it is possible to detect these Debug messages as a library consumer. (Unless you attach a visual studio to the visual studio attached to the program running (which is a mess))
## #40: Documentation on RabbitAuth.LogOn says nothing about the NetworkInformationException it might throw

How should somebody know this can happen without looking at the source?
## #41: Documentation is not even included in the NuGet version!

What's the point of documenting everything when nobody can read it?
## #42: PDB files are not included in the NuGet project

.pdb files help a ton when debugging programs.
## #43: InternetStabilityTester can be marked static

Instead of adding a private constructor (which should be used when dealing with singletons instead), just mark the class with `static`.
## #44: InternetStabilityTester returns true when there is no internet available

The name of the class implies that it checks for an internet connection (and not a connection to any network). Even if you connect your pc to a router not connected to the internet, InternetStabilityTester returns true.
## #45: InternetStabilityTester is useless

InternetStabilityTester can be replaced with `System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()`.

**Comment by Decagon** [comment]
I'd like to support swapit authentication but I don't see anything right off from PlayerIO. Does swapit just use the regular playerio.authenticate routine or something else?
